### ISSUE TITLE
Change "manage" button to Elipsis icon?

### ISSUE THREAD

**Issue by briancwald** [briancwald/dfs-admin#10]
For dropbuttons, I wonder if it makes sense to just make them the http://fontawesome.io/icon/ellipsis-v/ icon.

**Comment by mortenson** [comment]
There are places where I would prefer labels, ellipsis, and a configure/gear icon. I think we'll have to hard code a lot of cases and default on something like an ellipsis. Also, why aren't we using Material icons?

**Comment by briancwald** [comment]
We probably should yea, I forgot why I choose to not use them to be honest but I'm sure it would be fine and obviously more consistent with the other material stuff

**Comment by briancwald** [comment]
Oh yeah, it was because the sass integration method fontawesome has which makes it super easy to attach to a :before and :after elements whereas google fonts uses a sprite integration approach and prefers them to be displayed in the HTML. http://google.github.io/material-design-icons/

But I'm sure we could do it, just need to look at the implementation details more.

**Comment by briancwald** [comment]
I think at the very least we should place this for all table 'operations'

**Comment by briancwald** [comment]
<img width="1556" alt="screenshot 2017-06-20 08 05 52" src="https://user-images.githubusercontent.com/776942/27332295-54be88dc-558f-11e7-90e5-fc96398ebe82.png">
