### ISSUE TITLE
Mobile table pattern

### ISSUE THREAD

**Issue by briancwald** [briancwald/dfs-admin#11]
Currently there is no good method for viewing tables on mobile. The solution defined in materializecss ( https://materializecss.com/table.html) is not good enough given the number of tables in drupal.

**Comment by mortenson** [comment]
I vote table saw everywhere we can add it

**Comment by briancwald** [comment]
Yeah. I think it will take some work to get it to work universally as we would like, I spent some time in that awhile back, but just pulled it out to focus on my critical items

**Comment by briancwald** [comment]
Here is what I'm thinking. It essentially takes the table saw method and then uses material admin styling. 

- The first column + any operations are always exposed. 
- Arrow indicates status of open/closed
- Show All button allows users to expand all the 'columns' for each item to avoid having to click a bunch when searching for a specific item.

![repsonsive-table-style](https://user-images.githubusercontent.com/776942/27696724-608084bc-5cc0-11e7-944a-edc1d622f7c0.png)

**Comment by mortenson** [comment]
So we've got Tablesaw in for Views tables, but modules provide tables as well for language configuration, the field UI, the permissions page, and likely others. Are we just focusing this issue on responsive Views tables or should we do more?

**Comment by briancwald** [comment]
I think any table that we have operations in the last column we should do something to enhance that since we can be predictable. 

Aside from that, it would be hard to determine what is on the table, but tablesaw could be used in most cases. I think my next step will gather a list of all the tables that come OOTB in Drupal and determine any enhancements that can apply across them all.
