### ISSUE TITLE
FOUC on views 'add' button during page load

### ISSUE THREAD

**Issue by briancwald** [briancwald/dfs-admin#14]
When the View page loads, the add button shows unstyled dropdown that flashes on the screen before it compiles it into a button. 

Replicate:

- Visit a view page and see on DOM load.

![foac-views](https://user-images.githubusercontent.com/776942/27331600-36a9eca4-558c-11e7-9133-a5862c1d6e76.gif)

**Comment by mortenson** [comment]
Fixed here: https://github.com/briancwald/material_admin/commit/0471643d33735f8984f70ce67654033ba5fac390#diff-f0df95b2073b9120598c111eb1a0c998R902
