### ISSUE TITLE
Module uninstall page checkboxes

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#2]
They are not the same as the checkboxes in the module install page. I'm assuming they should be the same.

**Comment by briancwald** [comment]
Yes, I had overlooked that page - I updated it to include the switch and labels that make sense.

![screenshot 2017-05-12 15 10 20](https://cloud.githubusercontent.com/assets/776942/26013161/2ba7c914-3725-11e7-8bab-f18daf52cadd.png)

Im going to keep this issue open though,  I'd like to clean up the styling and add dropdown for the details of the module, similar to the module install page.

**Comment by briancwald** [comment]
- Cleaned up to match install page
- Add collapse for description requirements (if exisit)
- add warning text to highight the reason why you cannot uninstall.


<img width="1367" alt="screenshot 2017-05-16 08 11 33" src="https://cloud.githubusercontent.com/assets/776942/26105264/4e5a92f6-3a0f-11e7-8bb0-52c0ff6c35ac.png">

**Comment by briancwald** [comment]
@e0ipso can you review this page?

**Comment by e0ipso** [comment]
It looks great!

If you are looking for feeback, may I suggest looking at the login page next? Do you want me to creat a new issue?

😊

**Comment by briancwald** [comment]
Hmm, typically the admin login is controlled by the front end theme but I'd imagine in your use case it's the same thing, I can take a look to see what is possible. Thanks!

**Comment by briancwald** [comment]
@e0ipso please, make any tickets, some ill be aware of but others I will miss.. there are so many templates in core! plus it keeps me motivated.
