### ISSUE TITLE
Exposed filter and bulk operation improvements look awkward in the Views preview

### ISSUE THREAD

**Issue by mortenson** [briancwald/dfs-admin#23]
<img width="1274" alt="screen shot 2017-07-22 at 9 33 24 am" src="https://user-images.githubusercontent.com/2091002/28492922-d9f1f170-6ec0-11e7-8276-43fcd5f6e9c2.png">

The Views improvements were not tested in the Views preview area, and look pretty crazy. I'm guessing the same form structure/classes aren't present in the backend. Screenshot above is from the preview at `/admin/structure/views/view/content`.

**Comment by briancwald** [comment]
😳

________________________________

**Comment by mortenson** [comment]
Addressed in https://github.com/briancwald/material_admin/commit/d032b6e3d331612ed544d9106962165a63760a45
