### ISSUE TITLE
Some fields are missing the inline labels

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#3]
In the login screen the password field looks different from the username field.

![log in contenta json api 2017-05-20 06-59-05](https://cloud.githubusercontent.com/assets/1140906/26273144/0073d1ba-3d2a-11e7-9a47-de383aae8405.png)

**Comment by tormi** [comment]
Same with email field at `/user/register`.

**Comment by e0ipso** [comment]
As pointed out by @tormi, this also happens in other textfields.

![create new account contenta json api 2017-05-20 07-20-12](https://cloud.githubusercontent.com/assets/1140906/26273284/e9dececa-3d2c-11e7-8e09-2ebc6e727a60.png)

**Comment by briancwald** [comment]
Yes, I have this specifically called out locally (for the password field) though I'm trying to figure out a better way to deal with it than explicitly calling out the field types. Maybe there is not. 

Right now I need to add the text-input class to various field types.

**Comment by briancwald** [comment]
this commit will fix the ones you are referring to and I added a few more that I feel confident will display correctly with the inline format.

https://github.com/briancwald/material_admin/commit/c1a3a6fe7dcae5428517d697ab36c8083c5f562c#diff-dd9fb2940ad57bbbc916e5347106aed1R57

If there are more, we can add those to that array.
