### ISSUE TITLE
Consider bigger textareas

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#35]
Someone filed this issue in Contenta about Material Admin. I thought I'd surface it here.

https://github.com/contentacms/contenta_jsonapi/issues/178#issuecomment-325506458

**Comment by briancwald** [comment]
Two updates:

1) I added a preprocess function for textareas to set the default to a bigger (100 cols) width which is about ~700px (with max-width still set to 100% to avoid overflow). This is the widely accepted ideal width for a text area readability. (textareas also 'expand' vertically as you type in them to avoid having to scroll in the textarea.

2) @mortenson and I talked about a plan is to build a field widget to allow the user to set the columns or set to full width. To do this, we will need to do it as part of the support module:
https://github.com/briancwald/material_admin_support

I will create a ticket for the second item over on that project and close this one.
