### ISSUE TITLE
JSON API Extras UI is not usable

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#37]
![2017-09-14 16-15-32](https://user-images.githubusercontent.com/1140906/30446391-4fbe2cf0-9989-11e7-91a8-9a7850677431.png)

vs

![2017-09-14 20-22-29](https://user-images.githubusercontent.com/1140906/30446795-754d0ab2-998a-11e7-938c-167082da3af9.png)

**Comment by e0ipso** [comment]
You can see how the table headers are very confusing, and the checkboxes are gone in Material Admin.

**Comment by briancwald** [comment]
The best that can be done here is to display browser defaults, so I added a check in form-element.twig to add a wrapping class for no label and display the original checkbox.

**Comment by e0ipso** [comment]
> and display the original checkbox

Sounds good! The problem is also with the table headers.

**Comment by briancwald** [comment]
@e0ipso you referring to how the bullet list is displaying as chips?

**Comment by briancwald** [comment]
@e0ipso, with the latest dev release after we discussed on slack everything, seems to be looking good now --  Definition lists are now properly styled too, per the material design spec. 

<img width="1506" alt="screenshot 2017-09-19 11 25 08" src="https://user-images.githubusercontent.com/776942/30600360-387fa058-9d2d-11e7-9cb0-3c3c4b5b4c90.png">
