### ISSUE TITLE
container entity item action styling

### ISSUE THREAD

**Issue by briancwald** [briancwald/dfs-admin#39]
We should represent container entity items actions as if they were 'card actions' to avoid having too many buttons with z-depth. 

I am not sure where this should happen, as I want to affect all entity lists, but for example in a media field where you can select multiple items, here is what I am thinking it should look like.

### (Desired state)
<img width="954" alt="screen shot 2017-10-12 at 8 47 01 am" src="https://user-images.githubusercontent.com/776942/31496686-64cc41fc-af2a-11e7-85c8-1b6d7a8d3b7f.png">

### (Current state)

<img width="968" alt="screen shot 2017-10-12 at 8 47 24 am" src="https://user-images.githubusercontent.com/776942/31496721-7f7e8f78-af2a-11e7-8057-e70471011c0d.png">

**Comment by briancwald** [comment]
Added support for entity browser and defined a method for specific contrib overrides in the scss folder.

<img width="939" alt="screen shot 2017-10-20 at 10 01 30 am" src="https://user-images.githubusercontent.com/776942/31824655-bcc57ba4-b57d-11e7-9724-8f71d0d09b40.png">
<img width="959" alt="screen shot 2017-10-20 at 10 01 22 am" src="https://user-images.githubusercontent.com/776942/31824656-bcd852b0-b57d-11e7-9f6f-26be3bde61b1.png">

**Comment by briancwald** [comment]
@mortenson I think I covered all the different methods an entity can be added in a generic way by adding a wrapper and a handle for sorting, but I am not sure if I hit all the methods you can display those in the form display UI, is there anything I am missing?

**Comment by mortenson** [comment]
@briancwald This looks good to me, most of the forms I'm looking at look more clear now.
