### ISSUE TITLE
The "New" badge needs styles

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#4]
It needs (at least) some margin for readability.

![content contenta json api 2017-05-20 12-13-05](https://cloud.githubusercontent.com/assets/1140906/26274933/f6ba8016-3d55-11e7-88a6-3f29ff816109.png)

**Comment by briancwald** [comment]
@e0ipso with vanilla drupal my content page looks like this: 

<img width="1809" alt="screenshot 2017-05-20 12 58 44" src="https://cloud.githubusercontent.com/assets/776942/26277749/4baf73d2-3d5c-11e7-8acd-aa7b6a78d0e5.png">


Are you modifying that view somehow to remove the bulk operations?
 I'm not sure why I am not getting 'new' tag either.

**Comment by briancwald** [comment]
Got it, you start with minimal profile build which doesnt have any of the bulk operation features
<img width="1796" alt="screenshot 2017-05-20 13 08 38" src="https://cloud.githubusercontent.com/assets/776942/26277803/a7d054aa-3d5d-11e7-9862-3f73a01c7c1c.png">

 I have never built this profile as a starting point using Material Admin yet, I will poke around (and fix this issue).

**Comment by briancwald** [comment]
fixed drupal 'marker' span class to use badges css component. 
<img width="1796" alt="screenshot 2017-05-20 13 26 20" src="https://cloud.githubusercontent.com/assets/776942/26278023/5a2c3a9a-3d60-11e7-9f0e-0ff7bf9bfcc5.png">

**Comment by e0ipso** [comment]
Wow! You're killing it. Thanks.

On May 20, 2017 19:29, "Brian" <notifications@github.com> wrote:

fixed drupal 'marker' span class to use badges css component.
[image: screenshot 2017-05-20 13 26 20]
<https://cloud.githubusercontent.com/assets/776942/26278023/5a2c3a9a-3d60-11e7-9f0e-0ff7bf9bfcc5.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/briancwald/material_admin/issues/4#issuecomment-302887231>,
or mute the thread
