### ISSUE TITLE
Action buttons inherit default :focus styling

### ISSUE THREAD

**Issue by mortenson** [briancwald/dfs-admin#46]
<img width="418" alt="screen shot 2017-12-26 at 4 38 20 pm" src="https://user-images.githubusercontent.com/2091002/34367113-4ba91850-ea5b-11e7-9b4f-7c6035402600.png">

Action buttons, like those seen at `/node/add` or `/admin/structure/types/manage/article/fields`, have their red color hard-coded in CSS. It looks like some of the default button styling is not being overridden, because when focused the red action buttons are teal.

Instead of hard-coding colors in CSS, we should use add a color class like `red` on action buttons.

**Comment by briancwald** [comment]
Are you using dev? I think that was fixed recently in dev.

Nothing is hardcoded at all that I am aware of. it all uses variables defined in the [settings](https://github.com/briancwald/material_admin/blob/8.x-1.x/scss/_settings.scss#L120-L122) and color schema. 

[this](https://github.com/briancwald/material_admin/blob/8.x-1.x/scss/base/_common.scss#L162-L179) is where the action button colors are defined. This is where the action button is defined. Originally it only had the :hover defined, so it was inheriting the default .btn styling for :focus and :active. Now it should be fine.

**Comment by mortenson** [comment]
I was a few commits behind - I can confirm that this is fixed in dev.

By hard-coded I mean defined in SASS - it seems like with MaterializeCSS color classes are the way they want you to add colors to elements, not by targeting selectors, which is why I brought it up. Since this is fixed we can close this out if you want to keep the SASS the same.

**Comment by briancwald** [comment]
Yeah, I think in certain areas, like action buttons I am using the markup that Core provides so I cant do everything exactly how the framework wants without adding a bunch of extra markup or changing it, which I am trying to limit to avoid conflicts with newer versions of core or contrib modules. If you have a better idea of how to handle that, I am happy to reconfigure it, I just didn't think of anything easy.

**Comment by mortenson** [comment]
I think to really do this "right", we would have to find every instance where a class we could add with a preprocess or Twig is being added with `@extend` and change that. ex: for buttons: https://github.com/briancwald/material_admin/search?utf8=%E2%9C%93&q=extend+.btn&type=

This is a pretty big task so I think we can table it for now since my original bug report is fixed in dev.
