### ISSUE TITLE
Database update pages are unstyled

### ISSUE THREAD

**Issue by e0ipso** [briancwald/dfs-admin#50]
Hello!

Thanks again for all the work in this (awesome) theme. I found a bug, there seems to be missing CSS in the update pages.

![2018-03-04 08-33-47](https://user-images.githubusercontent.com/1140906/36943270-d55983ea-1f86-11e8-9cb9-76310ea27dac.png)

**Comment by e0ipso** [comment]
This happens in all the screens in the database update process.

**Comment by e0ipso** [comment]
![2018-03-04 09-02-40](https://user-images.githubusercontent.com/1140906/36943497-de966708-1f8a-11e8-8a62-e69b213cd638.png)

**Comment by briancwald** [comment]
Yikes! havent seen this yet, I'm on it.

**Comment by briancwald** [comment]
I have updated this and it works ok now on a base install. I can give contenta a try as well. 

<img width="1236" alt="screen shot 2018-03-10 at 10 19 03 am" src="https://user-images.githubusercontent.com/776942/37243762-c51af89a-244c-11e8-8bf1-c6231e8d94e2.png">

**Comment by briancwald** [comment]
@e0ipso  All seems good with Contenta as well. 

<img width="1297" alt="screen shot 2018-03-10 at 10 29 28 am" src="https://user-images.githubusercontent.com/776942/37243844-0889d29e-244e-11e8-8830-bc4339fd275e.png">
<img width="1309" alt="screen shot 2018-03-10 at 10 30 03 am" src="https://user-images.githubusercontent.com/776942/37243845-08984400-244e-11e8-8034-a61b855d084e.png">
